### ISSUE TITLE
nested parentheses in $

### ISSUE THREAD

**Issue by jkitchin** [rspeele/infix.el#1]
Would you expect this to work: ($ 1 / (1 + (exp x)))

It expands to: 
(/ 1  (1 + (exp x)))

Which isn't valid.

**Comment by rspeele** [comment]
Hi,

Good question. infix.el leaves nested s-expressions alone, precisely so that you can use regular functions like `(exp x)` in the midst of your infix expression.

So you have two ways of doing what you want:

either a. Use the `$` macro again in the nested s-expression: `($ 1 / ($ 1 + (exp x)))`
or b. Use curly braces instead, which infix.el processes for expression grouping: `($ 1 / { 1 + (exp x) })`

Due to some hacky symbol mangling, curly braces will also work without spaces around the infix operators: `($ 1/{1+(exp 1)})`

I'll add a note about this subject to the README.

Regards,
Robert

**Comment by rspeele** [comment]
I have added a couple clarifications to the README.
Please let me know if it still doesn't make sense.

(edit: after revisiting my code I also opened issue #2 and made a code change for it -- you might want to take a look at that issue)

Regards,
Robert

**Comment by jkitchin** [comment]
hm. Neither of those work for me.

```
#+BEGIN_SRC emacs-lisp :results code
(macroexpand '($ 1 / ($ 1 + (exp x))))
#+END_SRC

#+RESULTS:
#+BEGIN_SRC emacs-lisp
(/ 1
   ($ 1 +
      (exp x)))
#+END_SRC
```

with curly brackets I get

progn: Leftover terms in infix expression

**Comment by rspeele** [comment]
The first makes sense, because `macroexpand` does not recursively expand macros. It only does the first layer. See this example:

```elisp
(defmacro macro-square(x) `(* ,x ,x))
(macroexpand '(macro-square (macro-square 2)))
;; result doesn't have nested macros expanded: (* (macro-square 2) (macro-square 2))
```

For the "leftover terms in infix expression", make sure you are using:
`(macroexpand '($ 1 / { 1 + (exp x) }))`

and **not**:

`(macroexpand '($ 1 / { 1 + {exp x} }))`

**Comment by jkitchin** [comment]
Thanks. macroexpand-all does the trick with the recursive expansion it looks like. I think the leftover terms was from the nested macro.
